import os

#URL_DATABASE=os.getenv("DATABASE_URL") #al desplegar, para q se conecte a la base postgre
URL_DATABASE=os.getenv("DATABASE_URL")

#CSRF_TOKEN
CSRF_SECRET_KEY=os.getenv("CSRF_SECRET_KEY")

#OAUTH2
SECRET_KEY=os.getenv("SECRET_KEY")

ACCESS_TOKEN_EXPIRE_MINUTES=int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_DAYS=int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS"))

ALGORITHM="HS256"


#PROJECT_ID_GOOGLE='sawwwqafvxrrasfwqa-464421-t0'

#FIRST_ADMIN PASSWORD
FIRST_ADMIN_PASSWORD=os.getenv("FIRST_ADMIN_PASSWORD")
FIRST_ADMIN_EMAIL=os.getenv("FIRST_ADMIN_EMAIL")
FIRST_ADMIN_PHONE_NUMBER=os.getenv("FIRST_ADMIN_PHONE_NUMBER")
FIRST_ADMIN_PHONE_NUMBER_REGION=os.getenv("FIRST_ADMIN_PHONE_NUMBER_REGION")

#PAYMENT STRIPE
STRIPE_SECRET_KEY=os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET=os.getenv("STRIPE_WEBHOOK_SECRET")
CURRENCY=os.getenv("CURRENCY")

#There are some settings in cart_and_payment router about payments that could be changed

#SUCCESS AND CANCEL STRIPE URLS FRONTEND
SUCCESS_URL=os.getenv("SUCCESS_URL")
CANCEL_URL=os.getenv("CANCEL_URL")

#CREATE RESERVATION EXPIRATION TIME
CREATE_RESERVATION_EXPIRATION_TIME=int(os.getenv("CREATE_RESERVATION_EXPIRATION_TIME"))
#CHECKOUT_PAYMENT_EXPIRATION_TIME
CHECKOUT_PAYMENT_EXPIRATION_TIME=int(os.getenv("CHECKOUT_PAYMENT_EXPIRATION_TIME"))
#RELEASE_EXPIRED_RESERVATIONS_TIME
RELEASE_EXPIRED_RESERVATIONS_TIME=int(os.getenv("RELEASE_EXPIRED_RESERVATIONS_TIME"))



#ORIGINS
ORIGIN_1=os.getenv("ORIGIN_1")
ORIGIN_2=os.getenv("ORIGIN_2")

#ALLOWED HOSTS
ALLOWED_HOST_1=os.getenv("ALLOWED_HOST_1")
ALLOWED_HOST_2=os.getenv("ALLOWED_HOST_2")


#STRIPE CHECKOUT SESSIONS EXPIRATION TIME
CHECKOUT_SESSION_EXPIRATION_TIME=int(os.getenv("CHECKOUT_SESSION_EXPIRATION_TIME"))